# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YLTestSubspecDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'YLTestPodSpec','0.0.3'

  target 'YLTestSubspecDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YLTestSubspecDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
